### ISSUE TITLE
AI menu not showing up

### ISSUE THREAD

**Issue by hemangjoshi37a** [blueturtleai/gimp-stable-diffusion#2] opened 2022-09-20 11:59 UTC
Can you please let us know which exactly version of GIMP are you using because we cant find the AI menu in the munu bar. https://hjlabs.in

**Comment by blueturtleai** [comment] 2022-09-20 12:10
I'm using GIMP 2.10.8. Which version do you use?

**Comment by hemangjoshi37a** [comment] 2022-09-20 12:15
my version : 2.10.32

**Comment by hemangjoshi37a** [comment] 2022-09-20 12:16
I think i will just downgrade to yours. Thanks for the awesome script and solving my problem. awesome

**Comment by hemangjoshi37a** [comment] 2022-09-20 12:18
I tried : `sudo apt-get install gimp==2.10.8`

It Gives me the error that 
```

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package gimp is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Version '2.10.8' for 'gimp' was not found

```
![Screenshot from 2022-09-20 17-47-29](https://user-images.githubusercontent.com/12392345/191255721-eff73743-ca76-4619-b943-773907b5da1b.png)

**Comment by blueturtleai** [comment] 2022-09-20 12:21
You are welcome! Tbh, I don't think, that the problem is caused by the version difference. Please check again, that the gimp-stable-diffusion.py script is located in the plugin folder. And that it's really the .py and not the .ipynb script, which is the notebook.

**Comment by blueturtleai** [comment] 2022-09-20 12:31
Also, please restart GIMP after you copied the file to the plugin folder.

**Comment by hemangjoshi37a** [comment] 2022-09-21 09:53
I tried multiple possibilities copying the folder and different files but not any combination seems to work, I think it may be becuase I am using development branch of Ubuntu kinetic Kudu and It is something about that may be.

Also I tried restarting the app and also the computer but the problem still persists.

**Comment by blueturtleai** [comment] 2022-09-22 16:13
Sorry to hear, that the problem persists. Do you have the chance to try it with another setup, especially another OS?

**Comment by ReallyRad** [comment] 2022-09-22 18:25
I'm having the same problem on MacOS 12.3 with GIMP 2.10.32. I'm going to try on Windows now.

EDIT : doing chmod 755 on the python script seems to have done the trick. I will update you when I'm done completing the other steps.

**Comment by heitikei** [comment] 2022-09-23 09:03
Spitzer has left the building and forgot to set the vacation calendar. See you again my friend.

**Comment by blueturtleai** [comment] 2022-09-24 07:35
@hemangjoshi37a were you able to solve the problem by using chmod 755?

**Comment by hemangjoshi37a** [comment] 2022-09-24 07:54
> @hemangjoshi37a were you able to solve the problem by using chmod 755?

I was little busy in other projects but I will give it a try today evening.👍👍

**Comment by heitikei** [comment] 2022-09-24 09:17
Backseat driver here
Queue "import os" first
To will future proof future webspace4.

**Comment by blueturtleai** [comment] 2022-09-24 10:50
> Backseat driver here Queue "import os" first To future proof future webspace4.

How is this connected to this issue?

**Comment by heitikei** [comment] 2022-09-24 10:53
you are resolving OS issues one at a time, import OS first, and any future OS will already be included in the query?

**Comment by blueturtleai** [comment] 2022-09-25 17:09
In the meantime i got the confirmation, that’s its necessary to set the rights for the plugin py file to 755 on macOS. It‘s very likely that it‘s the same for Linux. I have updated the readme accordingly. If the problem persists after changing the permissions, please reopen this issue.

**Closed as completed by blueturtleai** 2022-09-25 17:09 UTC
